version: '3'
services:
  service-auth:
    image: registry.gitlab.com/ucconnect.devs/community-billboard/service-api:staging
    container_name: billboard-api
    env_file:
      - ".env-service-api.staging"
    networks:
      - billboard-network
    command: npm run start:prod
    restart: always


networks:
  billboard-network:
    external: true