export enum ErrorEnum {
    LOGIN_CONSENT_REQUIRED = 'LOGIN_CONSENT_REQUIRED',
    LOGIN_LOGIN_FAILED = 'LOGIN_LOGIN_FAILED',
    LOGIN_INVALID_TOKEN = 'LOGIN_INVALID_TOKEN',
    CREATE_USER_USER_EXISTED = 'CREATE_USER_USER_EXISTED',
    UPDATE_USER_USER_NOT_ACCEPT_CONSENT = 'UPDATE_USER_USER_NOT_ACCEPT_CONSENT',
    JWT_PROFILE_INVALID = 'JWT_INVALID',
    COMMUNITY_NOT_FOUND = 'COMMUNITY_NOT_FOUND',
    BOOST_INSUFFICIENT_COIN = 'BOOST_INSUFFICIENT_COIN',
    MEDIA_TRACK_NOT_FOUND='MEDIA_TRACK_NOT_FOUND',

}