export enum ErrorEnum {
    LOGIN_CONSENT_REQUIRED = 'LOGIN_CONSENT_REQUIRED',
    LOGIN_LOGIN_FAILED = 'LOGIN_LOGIN_FAILED',
    LOGIN_INVALID_TOKEN = 'LOGIN_INVALID_TOKEN',
    CREATE_USER_USER_EXISTED = 'CREATE_USER_USER_EXISTED',
    UPDATE_USER_USER_NOT_ACCEPT_CONSENT = 'UPDATE_USER_USER_NOT_ACCEPT_CONSENT',
    COMMUNITY_NOT_FOUND = 'COMMUNITY_NOT_FOUND',

}