export const EVENT_SUBSCRIBER_META_KEY = 'subscriber.event.name'
export enum EventName {
    USER_CREATED = 'USER_CREATED',
    USER_REQUEST_EMAIL_VERIFICATION = 'USER_REQUEST_EMAIL_VERIFICATION',
    USER_VERIFIED = 'USER_VERIFIED',
    USER_DELETED = 'USER_DELETED',
    USER_REQUESTED_EMAIL = 'USER_REQUESTED_EMAIL',
    FCM_TOPIC_NOTIFICATION = 'FCM_TOPIC_NOTIFICATION',
    FCM_DEVICE_NOTIFICATION = 'FCM_DEVICE_NOTIFICATION',
    CONTACT_SUPPORT = 'CONTACT_SUPPORT',
    USER_REQUEST_RESET_PASSWORD = 'USER_REQUEST_RESET_PASSWORD',
    CMS_ENTRY_UPDATE = 'CMS_ENTRY_UPDATE',
    CMS_ADS_UPDATE = 'CMS_ADS_UPDATE',
    PLAYBACK_STATS_CONTENT_WATCHED = 'PLAYBACK_STATS_CONTENT_WATCHED',
    SYNC = 'SYNC',
    BUFFER_DOWNLOADED = 'BUFFER_DOWNLOADED',
}
