export enum ProviderName {
    DATASOURCE = 'DATASOURCE',
    ENV_CONFIG = 'ENV_CONFIG',
    ENTITY = 'ENTITY',
    UNIT_OF_WORK = 'UNIT_OF_WORK',

    ORM_DATASOURCE = 'ORM_DATASOURCE',
    ORM_ENTITY = 'ORM_ENTITY',
    PROFILE_REPOSITORY = 'PROFILE_REPOSITORY',

}
