export enum ProviderName {
    DATASOURCE = 'DATASOURCE',
    ENV_CONFIG = 'ENV_CONFIG',
    ENTITY = 'ENTITY',
    UNIT_OF_WORK = 'UNIT_OF_WORK',

    ORM_DATASOURCE = 'ORM_DATASOURCE',
    ORM_ENTITY = 'ORM_ENTITY',
    PROFILE_REPOSITORY = 'PROFILE_REPOSITORY',
    USER_REPOSITORY = 'USER_REPOSITORY',
    ENCRYPTION_SERVICE = 'ENCRYPTION_SERVICE',
    AUTHENTICATION_SERVICE = 'AUTHENTICATION_SERVICE',
    TOKENIZATION_SERVICE = 'TOKENIZATION_SERVICE',
    HTTP_CLIENT = 'HTTP_CLIENT',
    LINE_REPOSITORY = 'LINE_REPOSITORY',
    ADMIN_REPOSITORY = 'ADMIN_REPOSITORY',
    COMMUNITY_REPOSITORY = 'COMMUNITY_REPOSITORY',
    CONTENT_REPOSITORY = 'CONTENT_REPOSITORY',
    SSE_SUBJECT = 'SSE_SUBJECT',

    ELASTIC_CLIENT = 'ELASTIC_CLIENT',
    ELASTIC_LOGGER = 'ELASTIC_LOGGER',

    SEARCH_REPOSITORY = 'SEARCH_REPOSITORY',
    TRACK_REPOSITORY = 'TRACK_REPOSITORY',
    ALBUM_REPOSITORY = 'ALBUM_REPOSITORY',
    ARTIST_REPOSITORY = 'ARTIST_REPOSITORY',

    USER_SERVICE = 'USER_SERVICE',
    REQUEST_CONTEXT = 'REQUEST_CONTEXT',

    STRAPI_CLIENT = 'STRAPI_CLIENT',
}
